Re-organised short-wave scripts to calculate k-coefficients and cloud optical properties fits as a part of the mk_sp_sw_* scripts.

diff --git a/gen_spec_files/sp_sw_dsa/mk_sp_sw_21_dsa b/gen_spec_files/sp_sw_dsa/mk_sp_sw_21_dsa
--- a/gen_spec_files/sp_sw_dsa/mk_sp_sw_21_dsa
+++ b/gen_spec_files/sp_sw_dsa/mk_sp_sw_21_dsa
@@ -7,15 +7,361 @@ NBANDS="21"
 
 . ../set_paths_sw
 
+################################################################################
+# Calculate k-coefficients
+################################################################################
+
+echo "Calculating k-coefficients."
+
+# Set paths to files
+HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
+HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
+HITRAN_O3="$HITRAN_DIR/03_hit12.par"
+HITRAN_N2O="$HITRAN_DIR/04_hit08.par"
+HITRAN_UV_N2O="$HITRAN_DIR/N2O-UV00.xsc"
+HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
+HITRAN_O2="$HITRAN_DIR/07_hit12.par"
+HITRAN_UV_O2="$HITRAN_DIR/07_UV06.par"
+HITRAN_SO2="$HITRAN_DIR/09_hit12.par"
+HITRAN_UV_SO2="$HITRAN_DIR/SO2_UV08.xsc"
+HITRAN_OCS="$HITRAN_DIR/19_hit12.par"
+HITRAN_UV_O3="$RAD_DATA/gases/ser_bdm_o3.xsc"
+JPL_UV_O2="$RAD_DATA/gases/jpl_o2.xsc"
+o3_pt_file="$RAD_DATA/gases/pt_o3_ser"
+o2_pt_file="$RAD_DATA/gases/pt_o2_jpl"
+n2o_pt_file="$RAD_DATA/gases/pt_n2o_uv"
+so2_pt_file="$RAD_DATA/gases/pt_so2_uv"
+ref_pt_file="$RAD_DATA/gases/ref_pt"
+
+if [ $RAD_BIN ] ; then
+  echo "Using code compiled in "$RAD_BIN
+else
+  echo "Path to code not set."
+  exit 1
+fi
+
+# Create skeleton spectral file
+SPECFILE="sp_sw_${NBANDS}_${SP_ID}_skel"
+rm -f ${SPECFILE}
+. mk_sp_sw_${NBANDS}_${SP_ID}_skel > /dev/null
+
+# Create directory for k-coefficients
+mkdir -p ${K_COEFF_DIR}
+
+# Construct weight argument
+WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"
+
+echo "Jobs running in background:"
+
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
+  echo "CO2 band 5"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 10 17 -c 2500.0 -i 1.0 -l 2 1.0e1 -t 4.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l \
+    -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
+    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
+    && echo "CO2 band 5 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
+  echo "CO2 band 6"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 2 1.0e1 -t 1.0e-2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
+    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
+    && echo "CO2 band 6 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/o3_u${NBANDS}_1-2l ] ; then
+  echo "O3 bands 1-2"
+  rm -f ${K_COEFF_DIR}/o3_u${NBANDS}_1-2l*
+  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
+    -R 1 2 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-3 \
+    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
+    -o ${K_COEFF_DIR}/o3_u${NBANDS}_1-2l \
+    -m ${K_COEFF_DIR}/o3_u${NBANDS}_1-2lm \
+    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o3_u${NBANDS}_1-2log \
+    && echo "O3 bands 1-2 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/o3_u${NBANDS}_3-4l ] ; then
+  echo "O3 bands 3-4"
+  rm -f ${K_COEFF_DIR}/o3_u${NBANDS}_3-4l*
+  Ccorr_k -F $o3_pt_file -X $HITRAN_UV_O3 \
+    -R 3 9 -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2 \
+    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
+    -o ${K_COEFF_DIR}/o3_u${NBANDS}_3-4l \
+    -m ${K_COEFF_DIR}/o3_u${NBANDS}_3-4lm \
+    -L $SW_DATA/o3_lbl_uv_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o3_u${NBANDS}_3-4log \
+    && echo "O3 bands 3-4 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/o3_s${NBANDS}_6l ] ; then
+  echo "O3 band 6"
+  rm -f ${K_COEFF_DIR}/o3_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O3 \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 3 1.0e-2 -t 1.0e-2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/o3_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/o3_s${NBANDS}_6lm \
+    -L $SW_DATA/o3_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o3_s${NBANDS}_6log \
+    && echo "O3 band 6 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/n2o_s${NBANDS}_6l ] ; then
+  echo "N2O band 6"
+  rm -f ${K_COEFF_DIR}/n2o_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_N2O \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 4 5.0e-3 -t 6.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/n2o_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/n2o_s${NBANDS}_6lm \
+    -L $SW_DATA/n2o_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/n2o_s${NBANDS}_6log \
+    && echo "N2O band 6 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_5l ] ; then
+  echo "CH4 band 5"
+  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
+    -R 10 17 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_5l \
+    -m ${K_COEFF_DIR}/ch4_s${NBANDS}_5lm \
+    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/ch4_s${NBANDS}_5log \
+    && echo "CH4 band 5 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_6l ] ; then
+  echo "CH4 band 6"
+  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/ch4_s${NBANDS}_6lm \
+    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/ch4_s${NBANDS}_6log \
+    && echo "CH4 band 6 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/o2_u${NBANDS}_1l ] ; then
+  echo "O2 band 1"
+  rm -f ${K_COEFF_DIR}/o2_u${NBANDS}_1l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_UV_O2 \
+    -R 1 1 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/o2_u${NBANDS}_1l \
+    -m ${K_COEFF_DIR}/o2_u${NBANDS}_1lm \
+    -L $SW_DATA/o2_lbl_uv_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o2_u${NBANDS}_1log \
+    && echo "CO2 band 5 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_3l ] ; then
+  echo "O2 band 3"
+  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_3l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
+    -R 3 3 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/o2_s${NBANDS}_3l \
+    -m ${K_COEFF_DIR}/o2_s${NBANDS}_3lm \
+    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o2_s${NBANDS}_3log \
+    && echo "O2 band 3 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_4l ] ; then
+  echo "O2 band 4"
+  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_4l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
+    -R 4 10 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 2.2e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/o2_s${NBANDS}_4l \
+    -m ${K_COEFF_DIR}/o2_s${NBANDS}_4lm \
+    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o2_s${NBANDS}_4log \
+    && echo "O2 band 4 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/o2_s${NBANDS}_5l ] ; then
+  echo "O2 band 5"
+  rm -f ${K_COEFF_DIR}/o2_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_O2 \
+    -R 11 17 -c 2500.0 -i 1.0 -l 7 2.3e3 -t 1.0e-2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/o2_s${NBANDS}_5l \
+    -m ${K_COEFF_DIR}/o2_s${NBANDS}_5lm \
+    -L $SW_DATA/o2_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/o2_s${NBANDS}_5log \
+    && echo "O2 band 5 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/so2_s${NBANDS}_6l ] ; then
+  echo "SO2 band 6"
+  rm -f ${K_COEFF_DIR}/so2_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_SO2 \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/so2_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/so2_s${NBANDS}_6lm \
+    -L $SW_DATA/so2_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/so2_s${NBANDS}_6log \
+    && echo "SO2 band 6 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/so2_u${NBANDS}_1-2l ] ; then
+  echo "SO2 band 1-2"
+  rm -f ${K_COEFF_DIR}/so2_u${NBANDS}_1-2l*
+  Ccorr_k -F $so2_pt_file -X $HITRAN_UV_SO2 \
+    -R 1 2 -c 2500.0 -i 1.0 -l 9 3.0e-4 -t 1.0e-3 \
+    -s ${SPECFILE} ${WGT} -q -r $ref_pt_file \
+    -o ${K_COEFF_DIR}/so2_u${NBANDS}_1-2l \
+    -m ${K_COEFF_DIR}/so2_u${NBANDS}_1-2lm \
+    -L $SW_DATA/so2_lbl_uv_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/so2_u${NBANDS}_1-2log \
+    && echo "SO2 band 1-2 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/ocs_s${NBANDS}_6l ] ; then
+  echo "OCS band 6"
+  rm -f ${K_COEFF_DIR}/ocs_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_OCS \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 25 1.0e-3 -t 1.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/ocs_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/ocs_s${NBANDS}_6lm \
+    -L $SW_DATA/ocs_lbl_sw_${PT_FILE}.nc \
+    > ${K_COEFF_DIR}/ocs_s${NBANDS}_6log \
+    && echo "OCS band 6 done" &
+fi
+
+echo "Jobs running in the foreground:"
+
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
+  echo "H2O lines band 3"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 3 3 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l \
+    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
+    && echo "H2O lines band 3 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
+  echo "H2O lines band 4"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 4 10 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l \
+    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
+    && echo "H2O lines band 4 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
+  echo "H2O lines band 5"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 11 17 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l \
+    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
+    && echo "H2O lines band 5 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
+  echo "H2O lines band 6"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 18 ${NBANDS} -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l \
+    -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
+    && echo "H2O lines band 6 done"
+fi
+
+if [ ! -s ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c ] ; then
+  echo "H2O self-broadened continuum"
+  rm -f ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c*
+  Ccorr_k -F ../pt_cont \
+    -R 3 ${NBANDS} -i 1.0 -ct 1 1 10.0 -t 1.0e-3 \
+    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
+    -k -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c \
+    -m ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6cm \
+    -L $SW_DATA/h2o-h2o_lbl_sw.nc \
+    -lw ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6clog \
+    && echo "H2O self-broadened continuum done"
+fi
+
+wait
+echo "Calculation of k-coefficients completed."
+
+################################################################################
+# Calculate optical properties
+################################################################################
+
+echo "Calculating cloud optical properties."
+
+WGT_SCTAVG="-${WGT:1}"
+
+mkdir -p ${CLD_COEFF_DIR}
+
+if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} ] ; then
+  echo 'Type 5 droplets'
+  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS}
+  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT_SCTAVG} \
+    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} \
+    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS} 1.e3 \
+    ${RAD_DATA}/cloud/scatter_drop_type5
+fi
+if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} ] ; then
+  echo 'Type 8 ice'
+  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS}
+  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT_SCTAVG} \
+    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} \
+    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS} 920 \
+    ${RAD_DATA}/cloud/scatter_ice_sw_type8
+fi
+
+echo "Calculation of cloud optical properties completed."
+
+################################################################################
+# Create spectral file
+################################################################################
+
+echo "Creating spectral file."
+
 # Create full path to spectral file
 SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}"
 
-# Remove old version
+mkdir -p ${SPEC_FILE_DIR}
 rm -f ${SPEC_FILE}
 rm -f ${SPEC_FILE}_k
 
 # Replace old k-coefficients by new k-coefficients in spectral file
-prep_spec << EOF
+prep_spec << EOF > mk_sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}_out
 sp_sw_${NBANDS}_${SP_ID}_skel
 n
 ${SPEC_FILE}
@@ -81,7 +427,7 @@ ${K_COEFF_DIR}/ocs_s${NBANDS}_6l
 EOF
 
 # Add cloud fits to spectral file
-prep_spec << EOF
+prep_spec << EOF >> mk_sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 a
 10
@@ -96,7 +442,7 @@ ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS}
 EOF
 
 # Add solar spectrum and Rayleigh scattering coefficients
-prep_spec << EOF
+prep_spec << EOF >> mk_sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 a
 2
@@ -109,7 +455,7 @@ a
 EOF
 
 # Tidy up and set continuum overlap method
-tidy_90 << EOF
+tidy_90 << EOF >> mk_sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 o
 1
@@ -138,3 +484,8 @@ n
 1
 -1
 EOF
+
+echo "Spectral file sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC} created. All done."
+echo "Please check mk_sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}_out for errors."
+
+exit 0
diff --git a/gen_spec_files/sp_sw_dsa_ar/mk_sp_sw_6_dsa_ar_lowch4 b/gen_spec_files/sp_sw_dsa_ar/mk_sp_sw_6_dsa_ar_lowch4
--- a/gen_spec_files/sp_sw_dsa_ar/mk_sp_sw_6_dsa_ar_lowch4
+++ b/gen_spec_files/sp_sw_dsa_ar/mk_sp_sw_6_dsa_ar_lowch4
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+NBANDS="6"
 SP_ID="dsa_ar_lowch4"
 SP_FLDR="dsa_ar"
 SOLAR_SPEC="sun"
@@ -7,51 +8,240 @@ PT_FILE="pt663"
 
 . ../set_paths_sw
 
+################################################################################
+# Calculate k-coefficients
+################################################################################
+
+echo "Calculating k-coefficients."
+
+# Set paths to files
+HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
+HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
+HITRAN_CH4="$HITRAN_DIR/06_hit12.par"
+
+if [ $RAD_BIN ] ; then
+  echo "Using code compiled in "$RAD_BIN
+else
+  echo "Path to code not set."
+  exit 1
+fi
+
+# Create skeleton spectral file
+SPECFILE="sp_sw_${NBANDS}_${SP_ID}_skel"
+rm -f ${SPECFILE}
+. mk_sp_sw_${NBANDS}_${SP_ID}_skel > /dev/null
+
+# Create directory for k-coefficients
+mkdir -p ${K_COEFF_DIR}
+
+# Construct weight argument
+WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"
+
+echo "Jobs running in background:"
+
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_4l ] ; then
+  echo "CO2 band 4"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_4l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 4 4 -c 2500.0 -i 1.0 -l 2 1.6e2 -t 4.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_4l -m ${K_COEFF_DIR}/co2_s${NBANDS}_4lm \
+    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s${NBANDS}_4log \
+    && echo "CO2 band 4 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
+  echo "CO2 band 5"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 5 5 -c 2500.0 -i 1.0 -l 2 1.6e2 -t 3.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
+    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
+    && echo "CO2 band 5 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
+  echo "CO2 band 6"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 6 6 -c 2500.0 -i 1.0 -l 2 1.6e2 -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
+    -L $SW_DATA/co2_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
+    && echo "CO2 band 6 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_5l ] ; then
+  echo "CH4 band 5"
+  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
+    -R 5 5 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_5l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_5lm \
+    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_5log \
+    && echo "CH4 band 5 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/ch4_s${NBANDS}_6l ] ; then
+  echo "CH4 band 6"
+  rm -f ${K_COEFF_DIR}/ch4_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CH4 \
+    -R 6 6 -c 2500.0 -i 1.0 -l 6 1.0e-2 -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/ch4_s${NBANDS}_6l -m ${K_COEFF_DIR}/ch4_s${NBANDS}_6lm \
+    -L $SW_DATA/ch4_lbl_sw_${PT_FILE}.nc > ${K_COEFF_DIR}/ch4_s${NBANDS}_6log \
+    && echo "CH4 band 6 done" &
+fi
+
+echo
+echo "Jobs running in foreground:"
+
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
+  echo "H2O lines band 3"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 3 3 -c 2500.0 -i 1.0 -l 1 1.0e2 -n 2  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
+    && echo "H2O lines band 3 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
+  echo "H2O lines band 4"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 4 4 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 3.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
+    && echo "H2O lines band 4 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
+  echo "H2O lines band 5"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 5 5 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 4.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
+    && echo "H2O lines band 5 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
+  echo "H2O lines band 6"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 6 6 -c 2500.0 -i 1.0 -l 1 1.0e2 -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
+    && echo "H2O lines band 6 done"
+fi
+
+if [ ! -s ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c ] ; then
+  echo "H2O self-broadened continuum"
+  rm -f ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c*
+  Ccorr_k -F ../pt_cont \
+    -R 3 6 -i 1.0 -ct 1 1 10.0 -t 1.0e-3 \
+    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
+    -k -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c \
+    -m ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6cm \
+    -L $SW_DATA/h2o-h2o_lbl_sw.nc \
+    -lw ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6clog \
+    && echo "H2O self-broadened continuum done"
+fi
+
+wait
+echo "Calculation of k-coefficients completed."
+
+################################################################################
+# Calculate optical properties
+################################################################################
+
+echo "Calculating cloud optical properties."
+
+WGT_SCTAVG="-${WGT:1}"
+
+mkdir -p ${CLD_COEFF_DIR}
+
+if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} ] ; then
+  echo 'Type 5 droplets'
+  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS}
+  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT_SCTAVG} \
+    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} \
+    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS} 1.e3 \
+    ${RAD_DATA}/cloud/scatter_drop_type5
+fi
+if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} ] ; then
+  echo 'Type 8 ice'
+  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS}
+  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT_SCTAVG} \
+    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} \
+    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS} 920 \
+    ${RAD_DATA}/cloud/scatter_ice_type8
+fi
+
+echo "Calculation of cloud optical properties completed."
+
+################################################################################
+# Create spectral file
+################################################################################
+
+echo "Creating spectral file."
+
 # Create full path to spectral file
 SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_6_${SP_ID}_${SOLAR_SPEC}"
 
-# Remove old version
+mkdir -p ${SPEC_FILE_DIR}
 rm -f ${SPEC_FILE}
 rm -f ${SPEC_FILE}_k
 
 # Replace old k-coefficients by new k-coefficients in spectral file
-prep_spec << EOF
-sp_sw_6_${SP_ID}_skel
+prep_spec << EOF > mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
+sp_sw_${NBANDS}_${SP_ID}_skel
 n
 ${SPEC_FILE}
 5
-${K_COEFF_DIR}/h2o_s6_3l
+${K_COEFF_DIR}/h2o_s${NBANDS}_3l
 5
 y
-${K_COEFF_DIR}/h2o_s6_4l
+${K_COEFF_DIR}/h2o_s${NBANDS}_4l
 5
 y
-${K_COEFF_DIR}/h2o_s6_5l
+${K_COEFF_DIR}/h2o_s${NBANDS}_5l
 5
 y
-${K_COEFF_DIR}/h2o_s6_6l
+${K_COEFF_DIR}/h2o_s${NBANDS}_6l
 19
-${K_COEFF_DIR}/h2o-h2o_s6_3-6c
+${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c
 5
 y
-${K_COEFF_DIR}/co2_s6_4l
+${K_COEFF_DIR}/co2_s${NBANDS}_4l
 5
 y
-${K_COEFF_DIR}/co2_s6_5l
+${K_COEFF_DIR}/co2_s${NBANDS}_5l
 5
 y
-${K_COEFF_DIR}/co2_s6_6l
+${K_COEFF_DIR}/co2_s${NBANDS}_6l
 5
 y
-${K_COEFF_DIR}/ch4_s6_5l
+${K_COEFF_DIR}/ch4_s${NBANDS}_5l
 5
 y
-${K_COEFF_DIR}/ch4_s6_6l
+${K_COEFF_DIR}/ch4_s${NBANDS}_6l
 -1
 EOF
 
 # Add cloud fits to spectral file
-prep_spec << EOF
+prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 a
 10
@@ -66,7 +256,7 @@ ${CLD_COEFF_DIR}/fit_sw_ice8_6
 EOF
 
 # Add solar spectrum and Rayleigh scattering coefficients
-prep_spec << EOF
+prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 a
 2
@@ -79,10 +269,15 @@ a
 EOF
 
 # Set continuum overlap treatment
-tidy_90 << EOF
+tidy_90 << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 o
 8
 1
 -1
 EOF
+
+echo "Spectral file sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC} created. All done."
+echo "Please check mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out for errors."
+
+exit 0
diff --git a/gen_spec_files/sp_sw_dsa_mars/mk_sp_sw_36_dsa_mars b/gen_spec_files/sp_sw_dsa_mars/mk_sp_sw_36_dsa_mars
--- a/gen_spec_files/sp_sw_dsa_mars/mk_sp_sw_36_dsa_mars
+++ b/gen_spec_files/sp_sw_dsa_mars/mk_sp_sw_36_dsa_mars
@@ -2,72 +2,280 @@
 
 SP_ID="dsa_mars"
 SP_FLDR="dsa_mars"
-NBAND="36"
+NBANDS="36"
 SOLAR_SPEC="pc"
 PT_FILE="pt793"
 
+# For a 10 bar atmosphere
+COL_H2O="1.0e+03" 
+COL_CO2="1.0e+05" # 1e6 ppmv in a 10 bar atmosphere
+COL_H2OC="100.0" # 10 bar atmosphere
+COL_CO2C="1.0e6" # 1e6 ppmv in a 10 bar atmosphere
+
 . ../set_paths_sw
 
-# Create full path to spectral file
-SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBAND}_${SP_ID}_${SOLAR_SPEC}"
+################################################################################
+# Calculate k-coefficients
+################################################################################
 
-# Remove old version
+echo "Calculating k-coefficients."
+
+# Set paths to files
+HITRAN_H2O="$HITRAN_DIR/01_hit12.par"
+HITRAN_CO2="$HITRAN_DIR/02_hit12.par"
+
+if [ $RAD_BIN ] ; then
+  echo "Using code compiled in "$RAD_BIN
+else
+  echo "Path to code not set."
+  exit 1
+fi
+
+# Create skeleton spectral file
+SPECFILE="sp_sw_${NBANDS}_${SP_ID}_skel"
+rm -f ${SPECFILE}
+. mk_sp_sw_${NBANDS}_${SP_ID}_skel > /dev/null
+
+# Create directory for k-coefficients
+mkdir -p ${K_COEFF_DIR}
+
+# Construct weight argument
+WGT="+S ${SOLAR_SPEC_DIR}/${SOLAR_SPEC}"
+
+echo "Jobs running in background:"
+
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_4l ] ; then
+  echo "CO2 band 4"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_4l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 4 11 -c 50000.0 -i 1.0 -l 2 ${COL_CO2} -t 4.0e-3  \
+    -sb gas_fractions -lp 2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_4l -m ${K_COEFF_DIR}/co2_s${NBANDS}_4lm \
+    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf1.0.nc > \
+    ${K_COEFF_DIR}/co2_s${NBANDS}_4log \
+    && echo "CO2 band 4 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_5l ] ; then
+  echo "CO2 band 5"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 12 25 -c 50000.0 -i 1.0 -l 2 ${COL_CO2} -t 4.0e-3  \
+    -sb gas_fractions -lp 2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_5l -m ${K_COEFF_DIR}/co2_s${NBANDS}_5lm \
+    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf1.0.nc > \
+    ${K_COEFF_DIR}/co2_s${NBANDS}_5log \
+    && echo "CO2 band 5 done" &
+fi
+if [ ! -s ${K_COEFF_DIR}/co2_s${NBANDS}_6l ] ; then
+  echo "CO2 band 6"
+  rm -f ${K_COEFF_DIR}/co2_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_CO2 \
+    -R 26 ${NBANDS} -c 50000.0 -i 1.0 -l 2 ${COL_CO2} -t 6.0e-3  \
+    -sb gas_fractions -lp 2 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/co2_s${NBANDS}_6l -m ${K_COEFF_DIR}/co2_s${NBANDS}_6lm \
+    -L $SW_DATA/co2_sblbl_sw_${PT_FILE}_gf1.0.nc > \
+    ${K_COEFF_DIR}/co2_s${NBANDS}_6log \
+    && echo "CO2 band 6 done" &
+fi
+
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_2l ] || \
+    [ ! -s $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc ] ; then
+  echo "H2O lines band 2"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_2l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 2 2 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -n 1 \
+    -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_2l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_2lm \
+    -L $SW_DATA/h2o_lbl_vis_${PT_FILE}.nc \
+     > ${K_COEFF_DIR}/h2o_s${NBANDS}_2log && echo "H2O lines band 2 done" &
+fi
+
+echo "Jobs running in foreground:"
+
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_3l ] ; then
+  echo "H2O lines band 3"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_3l*
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 3 3 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -n 2  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_3l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_3lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_3log \
+    && echo "H2O lines band 3 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_4l ] ; then
+  echo "H2O lines band 4"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_4l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 4 11 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_4l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_4lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_4log \
+    && echo "H2O lines band 4 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_5l ] ; then
+  echo "H2O lines band 5"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_5l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 12 25 -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_5l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_5lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_5log \
+    && echo "H2O lines band 5 done"
+fi
+if [ ! -s ${K_COEFF_DIR}/h2o_s${NBANDS}_6l ] ; then
+  echo "H2O lines band 6"
+  rm -f ${K_COEFF_DIR}/h2o_s${NBANDS}_6l*
+  Ccorr_k -F ../${PT_FILE} -D $HITRAN_H2O \
+    -R 26 ${NBANDS} -c 2500.0 -i 1.0 -l 1 ${COL_H2O} -t 6.0e-3  \
+    -s ${SPECFILE} ${WGT} -lk \
+    -k -x $RAD_DATA/continua/caviar_frn \
+    -o ${K_COEFF_DIR}/h2o_s${NBANDS}_6l -m ${K_COEFF_DIR}/h2o_s${NBANDS}_6lm \
+    -L $SW_DATA/h2o_lbl_swf_${PT_FILE}.nc \
+    -sm ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o_s${NBANDS}_6log \
+    && echo "H2O lines band 6 done"
+fi
+
+if [ ! -s ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c ] ; then
+  echo "H2O self-broadened continuum"
+  rm -f ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c*
+  Ccorr_k -F ../pt_cont \
+    -R 3 ${NBANDS} -i 1.0 -ct 1 1 ${COL_H2OC} -t 1.0e-3 \
+    -e $RAD_DATA/continua/caviar_s296 $RAD_DATA/continua/caviar_s260 \
+    -k -s ${SPECFILE} ${WGT} -lk \
+    -o ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c \
+    -m ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6cm \
+    -L $SW_DATA/h2o-h2o_lbl_sw.nc \
+    -lw ${K_COEFF_DIR}/h2o_s${NBANDS}_map.nc \
+    > ${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6clog \
+    && echo "H2O self-broadened continuum done"
+fi
+
+if [ ! -s ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c ] ; then
+  echo "CO2-CO2 CIA"
+  rm -f ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c*
+  Ccorr_k -F ../pt_cont -CIA ${CONT_DIR}/co2-co2.cia \
+    -R 26 ${NBANDS} -i 1.0 \
+    -ct 2 2 ${COL_CO2C} -t 1.0e-2 \
+    -k -s ${SPECFILE} +p -lk \
+    -o ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c \
+    -m ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6cm \
+    -L $SW_DATA/co2-co2_lbl_sw.nc \
+    > ${K_COEFF_DIR}/co2-co2_s${NBANDS}_6clog \
+    && echo "CO2-CO2 CIA done"
+fi
+
+wait
+echo "Calculation of k-coefficients completed."
+
+################################################################################
+# Calculate optical properties
+################################################################################
+
+echo "Calculating cloud optical properties."
+
+WGT_SCTAVG="-${WGT:1}"
+
+mkdir -p ${CLD_COEFF_DIR}
+
+if [ ! -s ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} ] ; then
+  echo 'Type 5 droplets'
+  rm -f ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS}
+  Cscatter_average -s ${SPECFILE} -P 1 -t ${WGT_SCTAVG} \
+    -f 5 ${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS} \
+    ${CLD_COEFF_DIR}/mon_sw_drop5_${NBANDS} 1.e3 \
+    ${RAD_DATA}/cloud/scatter_drop_type5
+fi
+if [ ! -s ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} ] ; then
+  echo 'Type 8 ice'
+  rm -f ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS}
+  Cscatter_average -s ${SPECFILE} -P 1 -w ${WGT_SCTAVG} \
+    -f 12 ${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS} \
+    ${CLD_COEFF_DIR}/mon_sw_ice8_${NBANDS} 920 \
+    ${RAD_DATA}/cloud/scatter_ice_sw_type8
+fi
+
+echo "Calculation of cloud optical properties completed."
+
+################################################################################
+# Create spectral file
+################################################################################
+
+echo "Creating spectral file."
+
+# Create full path to spectral file
+SPEC_FILE="${SPEC_FILE_DIR}/sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}"
+
+mkdir -p ${SPEC_FILE_DIR}
 rm -f ${SPEC_FILE}
 rm -f ${SPEC_FILE}_k
 
 # Add k-coefficients to spectral file
-prep_spec << EOF
-sp_sw_${NBAND}_${SP_ID}_skel
+prep_spec << EOF > mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
+sp_sw_${NBANDS}_${SP_ID}_skel
 n
 ${SPEC_FILE}
 5
-${K_COEFF_DIR}/h2o_s${NBAND}_2l
+${K_COEFF_DIR}/h2o_s${NBANDS}_2l
 5
 y
-${K_COEFF_DIR}/h2o_s${NBAND}_3l
+${K_COEFF_DIR}/h2o_s${NBANDS}_3l
 5
 y
-${K_COEFF_DIR}/h2o_s${NBAND}_4l
+${K_COEFF_DIR}/h2o_s${NBANDS}_4l
 5
 y
-${K_COEFF_DIR}/h2o_s${NBAND}_5l
+${K_COEFF_DIR}/h2o_s${NBANDS}_5l
 5
 y
-${K_COEFF_DIR}/h2o_s${NBAND}_6l
+${K_COEFF_DIR}/h2o_s${NBANDS}_6l
 19
-${K_COEFF_DIR}/h2o-h2o_s${NBAND}_3-6c
+${K_COEFF_DIR}/h2o-h2o_s${NBANDS}_3-6c
 5
 y
-${K_COEFF_DIR}/co2_s${NBAND}_4l
+${K_COEFF_DIR}/co2_s${NBANDS}_4l
 5
 y
-${K_COEFF_DIR}/co2_s${NBAND}_5l
+${K_COEFF_DIR}/co2_s${NBANDS}_5l
 5
 y
-${K_COEFF_DIR}/co2_s${NBAND}_6l
+${K_COEFF_DIR}/co2_s${NBANDS}_6l
 19
 y
-${K_COEFF_DIR}/co2-co2_s${NBAND}_6c
+${K_COEFF_DIR}/co2-co2_s${NBANDS}_6c
 -1
 EOF
 
 # Add cloud fits to spectral file
-prep_spec << EOF
+prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 a
 10
 5
-${CLD_COEFF_DIR}/fit_sw_drop5_${NBAND}
+${CLD_COEFF_DIR}/fit_sw_drop5_${NBANDS}
 1.70000E-06 5.00000E-05
 12
 8
-${CLD_COEFF_DIR}/fit_sw_ice8_${NBAND}
+${CLD_COEFF_DIR}/fit_sw_ice8_${NBANDS}
 8.00000E-06 3.00000E-04
 -1
 EOF
 
 # Add solar spectrum and Rayleigh scattering coefficients
-prep_spec << EOF
+prep_spec << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 a
 2
@@ -82,7 +290,7 @@ EOF
 
 # Rearrange so the major gas is listed first for each band and
 # gases are removed from bands where absorption is very weak.
-tidy_90 << EOF
+tidy_90 << EOF >> mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out
 ${SPEC_FILE}
 o
 1
@@ -106,3 +314,8 @@ n
 0
 -1
 EOF
+
+echo "Spectral file sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC} created. All done."
+echo "Please check mk_sp_sw_${NBANDS}_${SP_ID}_${SOLAR_SPEC}_out for errors."
+
+exit 0
